dist: trusty
sudo: false

language: d
os:
 - linux
 #- osx
d:
 - dmd
 - ldc
 
script:
 # tests + coverage
 - dub build --build=unittest-cov --config=compiler --compiler=${DC}
 - echo "unit b;" > b.ya && bin/yatol -v -p -a -t b.ya <<< "unit a;"
 # release build
 - dub --build=release --config=compiler --compiler=${DC}
 - dub build --build=release --config=library --compiler=${DC}
 # test w/ files
 - if [ "$DC" == "dmd" ]; then dmd=dmd; elif [ "$DC" == "ldc2" ]; then dmd=ldmd2; fi
 - $dmd -run tests/test.d
 # grammar
 - cd grammar && dub run --config=generate && dub run --config=test

after_success:
 - bash <(curl -s https://codecov.io/bash)
