dist: trusty
sudo: false

language: d
os:
 - linux
 #- osx
d:
 - dmd
 - dmd-nightly
 - ldc
 - ldc-beta 
 
script:
 - dub --build=unittest --config=compiler --compiler=${DC}
 - dub --build=release --config=compiler --compiler=${DC}
 - dub build --build=release --config=library --compiler=${DC}
